### ISSUE TITLE
Code release and reproducing the results

### ISSUE THREAD

**Issue by WalBouss** [Seonghoon-Yu/Zero-shot-RIS#1]
Thank you for your great work!
I was wondering if you plan to release your code anytime soon. 
I have been trying to reproduce the results, but I always get a few points lower performance than the one stated in the paper (for both _oIoU_ and _mIou_). 
I have checked the upper-bond limit of the mask proposal (FreeSOLO) and I get the same results as the paper, but I may be missing some implementation details/tricks.

**Comment by Seonghoon-Yu** [comment]
Thanks for your attention to our works
We released code
You could reproduce the results by following the provided instructions.
However, there may be slight variants in the performance (higher or lower around 0.0X points) depending on the version of python package or GPU environment.
We believe that these differences (higher or lower), which occur on each dataset split, are negligible and have minimal impact.
Thanks.
