### ISSUE TITLE
FreeSOLO_R101_30k_pl.pth  is unavailable

### ISSUE THREAD

**Issue by lcl-git-3d** [Seonghoon-Yu/Zero-shot-RIS#5]
![image](https://github.com/Seonghoon-Yu/Zero-shot-RIS/assets/125371176/88ee588a-5c97-4844-8386-4865e297a25b)

**Comment by charon517-517** [comment]
> ![image](https://private-user-images.githubusercontent.com/125371176/292210169-88ee588a-5c97-4844-8386-4865e297a25b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjkxMzYsIm5iZiI6MTcwNDcyODgzNiwicGF0aCI6Ii8xMjUzNzExNzYvMjkyMjEwMTY5LTg4ZWU1ODhhLTVjOTctNDg0NC04Mzg2LTQ4NjVlMjk3YTI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTQ3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzQyNGE5NjdmODU0MTg0ZDJkY2YwYzllNjZmNDgwZmQ5MzYwNTNiZDEzYjU3M2FlNDQyM2E3NDZhODg2NmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B8HwlYF80kk3SjipOXBdgRNTwDewHcjQW3N869GK0lQ)

maybe you can try this
https://github.com/NVlabs/FreeSOLO/issues/16#issuecomment-1869573024

**Comment by rabinadk1** [comment]
Still getting this issue, how to resolve this?

**Comment by seygodin** [comment]
I have this issue too.

**Comment by seamoon224** [comment]
can be downloaded from:
https://github.com/NVlabs/FreeSOLO/issues/16

**Comment by seamoon224** [comment]
As for datasets, refer to:
https://github.com/lichengunc/refer/issues/14
